// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package auth_repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateUserByCredential(ctx context.Context, arg CreateUserByCredentialParams) (User, error)
	CreateUserByGoogle(ctx context.Context, arg CreateUserByGoogleParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
