// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package auth_repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles(user_id, name)
VALUES ($1, $2)
ON CONFLICT (user_id)
DO UPDATE SET
  name = COALESCE(EXCLUDED.name, profiles.name),
  updated_at = CURRENT_TIMESTAMP
RETURNING id, name, job_title, description, resume_key, user_id, created_at, updated_at
`

type CreateProfileParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Name   pgtype.Text `json:"name"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.UserID, arg.Name)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.JobTitle,
		&i.Description,
		&i.ResumeKey,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserByCredential = `-- name: CreateUserByCredential :one
INSERT INTO users(email, password)
VALUES ($1, $2)
RETURNING id, email, password, access_token, refresh_token, created_at, updated_at
`

type CreateUserByCredentialParams struct {
	Email    string      `json:"email"`
	Password pgtype.Text `json:"password"`
}

func (q *Queries) CreateUserByCredential(ctx context.Context, arg CreateUserByCredentialParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserByCredential, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserByGoogle = `-- name: CreateUserByGoogle :one
INSERT INTO users(email, access_token, refresh_token)
VALUES ($1, $2, $3)
ON CONFLICT(email)
DO UPDATE SET
  access_token = EXCLUDED.access_token
RETURNING id, email, password, access_token, refresh_token, created_at, updated_at
`

type CreateUserByGoogleParams struct {
	Email        string      `json:"email"`
	AccessToken  pgtype.Text `json:"access_token"`
	RefreshToken pgtype.Text `json:"refresh_token"`
}

func (q *Queries) CreateUserByGoogle(ctx context.Context, arg CreateUserByGoogleParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserByGoogle, arg.Email, arg.AccessToken, arg.RefreshToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, access_token, refresh_token, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, password, access_token, refresh_token, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
