from .loader import(
  JD_EXTRACTOR_PROMPT,
  USER_CONTEXT_PROMPT,
  SEARCH_COMPANY_PROMPT,
  JOB_PROFILE_PROMPT,
  COMPARE_USER_SKILLS_TO_JD_PROMPT,
  COVER_LETTER_PROMPT,
  LINKEDIN_NOTE_PROMPT,
  COLD_MAIL_PROMPT
)