// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package document_repository

import (
	"context"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (key, user_id)
VALUES ($1, $2)
RETURNING id, key, user_id, created_at, updated_at
`

type CreateDocumentParams struct {
	Key    string    `json:"key"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument, arg.Key, arg.UserID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :one
DELETE FROM documents
WHERE id = $1 and user_id = $2
RETURNING id, key, user_id, created_at, updated_at
`

type DeleteDocumentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, deleteDocument, arg.ID, arg.UserID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentById = `-- name: GetDocumentById :one
SELECT id, key, user_id, created_at, updated_at
FROM documents
WHERE id = $1
`

func (q *Queries) GetDocumentById(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentById, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByUserAndId = `-- name: GetDocumentByUserAndId :one
SELECT id, key, user_id, created_at, updated_at
FROM documents
WHERE id = $1 AND user_id = $2
`

type GetDocumentByUserAndIdParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetDocumentByUserAndId(ctx context.Context, arg GetDocumentByUserAndIdParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByUserAndId, arg.ID, arg.UserID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByUserId = `-- name: GetDocumentByUserId :many
SELECT id, key, user_id, created_at, updated_at
FROM documents
WHERE user_id = $1
ORDER BY
  CASE WHEN $4 = 'asc'  THEN created_at END ASC,
  CASE WHEN $4 = 'desc' THEN created_at END DESC,
  created_at DESC
LIMIT COALESCE($2, 5)
OFFSET COALESCE($3, 0)
`

type GetDocumentByUserIdParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
}

func (q *Queries) GetDocumentByUserId(ctx context.Context, arg GetDocumentByUserIdParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentByUserId,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
