// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package document_repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActionType string

const (
	ActionTypeReview       ActionType = "review"
	ActionTypeApplyNote    ActionType = "apply_note"
	ActionTypeCoverLetter  ActionType = "cover_letter"
	ActionTypeLinkedinNote ActionType = "linkedin_note"
	ActionTypeColdMail     ActionType = "cold_mail"
)

func (e *ActionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActionType(s)
	case string:
		*e = ActionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActionType: %T", src)
	}
	return nil
}

type NullActionType struct {
	ActionType ActionType `json:"action_type"`
	Valid      bool       `json:"valid"` // Valid is true if ActionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActionType) Scan(value interface{}) error {
	if value == nil {
		ns.ActionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActionType), nil
}

type StatusType string

const (
	StatusTypeCOMPLETED  StatusType = "COMPLETED"
	StatusTypePROCESSING StatusType = "PROCESSING"
	StatusTypeQUEUED     StatusType = "QUEUED"
	StatusTypePENDING    StatusType = "PENDING"
	StatusTypeFAILED     StatusType = "FAILED"
)

func (e *StatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusType(s)
	case string:
		*e = StatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusType: %T", src)
	}
	return nil
}

type NullStatusType struct {
	StatusType StatusType `json:"status_type"`
	Valid      bool       `json:"valid"` // Valid is true if StatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.StatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusType), nil
}

type Document struct {
	ID        uuid.UUID          `json:"id"`
	Key       string             `json:"key"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID        uuid.UUID          `json:"id"`
	Action    ActionType         `json:"action"`
	DocKey    string             `json:"doc_key"`
	UserQuery string             `json:"user_query"`
	Status    NullStatusType     `json:"status"`
	SessionID string             `json:"session_id"`
	JdText    string             `json:"jd_text"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Profile struct {
	ID          uuid.UUID          `json:"id"`
	Name        pgtype.Text        `json:"name"`
	JobTitle    pgtype.Text        `json:"job_title"`
	Description pgtype.Text        `json:"description"`
	ResumeKey   pgtype.Text        `json:"resume_key"`
	UserID      uuid.UUID          `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	Password     pgtype.Text        `json:"password"`
	AccessToken  pgtype.Text        `json:"access_token"`
	RefreshToken pgtype.Text        `json:"refresh_token"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
