// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package document_repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	DeleteDocument(ctx context.Context, arg DeleteDocumentParams) (Document, error)
	GetDocumentById(ctx context.Context, id uuid.UUID) (Document, error)
	GetDocumentByUserAndId(ctx context.Context, arg GetDocumentByUserAndIdParams) (Document, error)
	GetDocumentByUserId(ctx context.Context, arg GetDocumentByUserIdParams) ([]Document, error)
}

var _ Querier = (*Queries)(nil)
