// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user_repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteProfile(ctx context.Context, userID uuid.UUID) (Profile, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error)
	GetUserInformation(ctx context.Context, id uuid.UUID) (GetUserInformationRow, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
}

var _ Querier = (*Queries)(nil)
