// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package user_repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProfile = `-- name: DeleteProfile :one
DELETE FROM profiles
WHERE user_id = $1
RETURNING id, name, job_title, description, resume_key, primary_resume_key, user_id, created_at, updated_at
`

func (q *Queries) DeleteProfile(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, deleteProfile, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.JobTitle,
		&i.Description,
		&i.ResumeKey,
		&i.PrimaryResumeKey,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id, email, password, access_token, refresh_token, created_at, updated_at
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email
FROM users
WHERE id = $1
`

type GetUserByIdRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const getUserInformation = `-- name: GetUserInformation :one
SELECT p.id AS profile_id, u.email, p.name, p.job_title, p.description, p.resume_key, p.primary_resume_key
FROM users u
JOIN profiles p
ON u.id = p.user_id
WHERE u.id = $1
`

const getUserInformationLegacy = `
SELECT p.id AS profile_id, u.email, p.name, p.job_title, p.description, p.resume_key
FROM users u
JOIN profiles p
ON u.id = p.user_id
WHERE u.id = $1
`

type GetUserInformationRow struct {
	ProfileID        uuid.UUID   `json:"profile_id"`
	Email            string      `json:"email"`
	Name             pgtype.Text `json:"name"`
	JobTitle         pgtype.Text `json:"job_title"`
	Description      pgtype.Text `json:"description"`
	ResumeKey        pgtype.Text `json:"resume_key"`
	PrimaryResumeKey pgtype.Text `json:"primary_resume_key"`
}

func (q *Queries) GetUserInformation(ctx context.Context, id uuid.UUID) (GetUserInformationRow, error) {
	row := q.db.QueryRow(ctx, getUserInformation, id)
	var i GetUserInformationRow
	err := row.Scan(
		&i.ProfileID,
		&i.Email,
		&i.Name,
		&i.JobTitle,
		&i.Description,
		&i.ResumeKey,
		&i.PrimaryResumeKey,
	)
	return i, err
}

func (q *Queries) GetUserInformationLegacy(ctx context.Context, id uuid.UUID) (GetUserInformationRow, error) {
	row := q.db.QueryRow(ctx, getUserInformationLegacy, id)
	var i GetUserInformationRow
	err := row.Scan(
		&i.ProfileID,
		&i.Email,
		&i.Name,
		&i.JobTitle,
		&i.Description,
		&i.ResumeKey,
	)
	return i, err
}

const setPrimaryResume = `-- name: SetPrimaryResume :one
UPDATE profiles p
SET primary_resume_key = $2,
    resume_key = $2
WHERE p.user_id = $1
  AND EXISTS (
    SELECT 1
    FROM documents d
    WHERE d.user_id = $1
      AND d.key = $2
  )
RETURNING id, name, job_title, description, resume_key, primary_resume_key, user_id, created_at, updated_at
`

type SetPrimaryResumeParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ResumeKey string    `json:"resume_key"`
}

func (q *Queries) SetPrimaryResume(ctx context.Context, arg SetPrimaryResumeParams) (Profile, error) {
	row := q.db.QueryRow(ctx, setPrimaryResume, arg.UserID, arg.ResumeKey)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.JobTitle,
		&i.Description,
		&i.ResumeKey,
		&i.PrimaryResumeKey,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET 
  name = COALESCE($3, name),
  job_title = COALESCE($4, job_title),
  description = COALESCE($5, description),
  resume_key = COALESCE($6, resume_key),
  primary_resume_key = COALESCE($7, primary_resume_key)
WHERE id = $1 AND user_id = $2
RETURNING id, name, job_title, description, resume_key, primary_resume_key, user_id, created_at, updated_at
`

type UpdateProfileParams struct {
	ID               uuid.UUID   `json:"id"`
	UserID           uuid.UUID   `json:"user_id"`
	Name             pgtype.Text `json:"name"`
	JobTitle         pgtype.Text `json:"job_title"`
	Description      pgtype.Text `json:"description"`
	ResumeKey        pgtype.Text `json:"resume_key"`
	PrimaryResumeKey pgtype.Text `json:"primary_resume_key"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.JobTitle,
		arg.Description,
		arg.ResumeKey,
		arg.PrimaryResumeKey,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.JobTitle,
		&i.Description,
		&i.ResumeKey,
		&i.PrimaryResumeKey,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
