// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package agent_repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserResume = `-- name: GetUserResume :one
SELECT resume_key
FROM profiles
WHERE user_id = $1
`

func (q *Queries) GetUserResume(ctx context.Context, userID uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserResume, userID)
	var resume_key pgtype.Text
	err := row.Scan(&resume_key)
	return resume_key, err
}
