// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package agent_repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetUserResume(ctx context.Context, userID uuid.UUID) (pgtype.Text, error)
}

var _ Querier = (*Queries)(nil)
